### PR TITLE
updates for Titan

### PR DESCRIPTION
**Pull request by wguanicedew**
1) with self.value.get_lock() throws some errors at Titan, but it works with acquire and release
2)Titan is using the yampl compiled by AthenaMP, the version is old and doesn't support timeout parameter.
3)Titan worker node doesn't have outbound connections. It cannot reach the condition db. It's using locally installed dbrelease.

### CODE REVIEW

**Comment by jtchilders** [comment]
Hi Wen, 
For (2) please increase the sleep time to 1 second so we are not utilizing too much CPU performing this loop.
For (3) this should not be needed. Theta also does not have network connection. So remove this and resubmit the pull request. If your job is trying to connect to Frontier, try adding 'unset FRONTIER_SERVER' to your submit template that Yoda uses to run Athena.
Taylor

**Comment by wguanicedew** [comment]
I will test 3). This one is suggested by Vakho.

**Comment by jtchilders** [comment]
To give you an example, I use the template given by 
https://github.com/PanDAWMS/panda-yoda/blob/master/templates/ThetaSubmitTF.sh
You can see the 'unset FRONTIER_SERVER' there. I also copy the xml files to a local working directory because Vakho found this to improve performance during initialization. 

I can confirm that jobs running on Theta today include this AND the '--dbrelease=all:current' but still run properly.

If this is a must for you, we need to find a better way to allow sites to adjust the Job definitions coming from Harvester that does not include source code hacks.

**Comment by wguanicedew** [comment]
I tested with 'unset FRONTIER_SERVER' and also with adding '--cmtextratags=ATLAS,useDBRelease' to asetup.sh. But it still doesn't work if I don't remove DBRelase in the joboptions.

**Comment by dougbenjamin** [comment]
Hi,

   We need to understand why at ALCF Theta unset FRONTIER_SERVER works but not at Titan.

Regards,
Doug

**Comment by jtchilders** [comment]
Committed some of these updates in version 0.6 but will still need to implement the 'DBRelease' plugin.

**Pull request closed without merging**
